name: AvatarProject
main: com.avatarproject.core.AvatarProjectCore
version: ${project.version}
authors: [avatarproject]
depend: [AbilityAPI]
softdepend: [WorldGuard]

commands:
  avatar:
    usage: /avatar
    aliases: [avatarproject, ap, bending, bend, b, thelastairbender, legendofkorra, lok, korra]
    description: Initial command for AvatarProject-Core

permissions:
  avatar.admin:
    default: OP
    description: Admin access to all of AvatarProject-Core
    children:
      avatar.player: true
      avatar.command.add: true
      avatar.command.add.other: true
      avatar.command.choose.rechoose: true
      avatar.command.toggle.other: true
  avatar.player:
    default: true
    description: Player access to basic parts of AvatarProject-Core
    children:
      avatar.command.bind: true
      avatar.command.choose: true
      avatar.command.clear: true
      avatar.command.help: true
      avatar.command.toggle: true
      avatar.command.version: true
      avatar.command.who: true
  avatar.fire:
    default: true
    description: Access to all the fire abilities in AvatarProject-Core
    children:
      avatar.ability.fire.fireblast: true
